spring:
  application:
    name: notificator-front

  thymeleaf:
    cache: false

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8084

notificator:
  api:
    url: http://jgf78.duckdns.org:8083
    messages-path: /api/messages/send
    send-pin-path: /api/messages/sendPin 
    send-poll-path: /api/messages/sendPoll
    send-file-path: /api/messages/sendFile

logging:
  file:
    path: ${LOG_PATH:./target/}
    name: ${spring.application.name}

  level:
    com.julian: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.boot: ${LOG_LEVEL_SPRING_BOOT:INFO}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    